# Generated by Django 2.2.6 on 2019-10-06 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tricks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='codetrick',
            name='code',
            field=models.TextField(default='', max_length=5000),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='codetrick',
            name='description',
            field=models.TextField(max_length=1000),
        ),
    ]
