# Generated by Django 2.2.6 on 2019-10-06 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tricks', '0002_auto_20191006_1344'),
    ]

    operations = [
        migrations.AddField(
            model_name='codetrick',
            name='updated_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='codetrick',
            name='create_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
